### ISSUE TITLE
Missing Command HRANDFIELD

### ISSUE THREAD

**Issue by hcwilhelm** [zio/zio-redis#342]
According to https://redis.io/commands/hrandfield Redis support the command HRANDFIELD, but this command is missing in the Hashes API.

## Tasks ##

- [ ] Implement the command
- [ ] Add tests for the command
- [ ] Add support for this command to the TestExecutor

**Comment by jgoday** [comment]
@hcwilhelm I have try to implement this with this PR #370.
I have implemented two different methods depending on the return value (field or array of fields).
Is this a valid approach ?

**Comment by hcwilhelm** [comment]
@jgoday i will review it in the next couple of days. But from what you described this approach sounds right to me. We split out different methods depending on the return type.
