### ISSUE TITLE
Return Type not correct for HMSET

### ISSUE THREAD

**Issue by hcwilhelm** [zio/zio-redis#343]
HMSET is returning Unit only if HMSET is called with multiple fields and values, if called with only one field and value it is returning Unit. https://redis.io/commands/hmset

In the current implementation, we always expect Unit.

```
  final def hmSet(
    key: String,
    pair: (String, String),
    pairs: (String, String)*
  ): ZIO[RedisExecutor, RedisError, Unit] =
    HmSet.run((key, (pair, pairs.toList)))
```

## Tasks ##

- [ ] Implement two versions of HMSET depending on the output type
- [ ] Implement tests for the two versions and properly test the different outputs
- [ ] Implement support for both versions in the TestExecutor

**Comment by jxnu-liguobin** [comment]
As per Redis 4.0.0, HMSET is considered deprecated. Please prefer HSET in new code.

Do we need to mark it?

**Comment by hcwilhelm** [comment]
Good question, maybe we shouldn't offer HMSET at all.

**Comment by jxnu-liguobin** [comment]
> Good question, maybe we shouldn't offer HMSET at all.

4.0 is not too old. It can be provided. By the way, when I use the `HMSET`, both get a `OK`. What's the problem?

**Comment by hcwilhelm** [comment]
You are right there isn't any problem, I misread the example command output. I will close the issue

**Comment by hcwilhelm** [comment]
This isn't an issue. HMSET returns unit in all cases
